# mypy: ignore-errors
# flake8: noqa

# This file is autogenerated by /metadata-ingestion/scripts/avro_codegen.py
# Do not modify manually!

# pylint: skip-file
# fmt: off
# isort: skip_file
from .....schema_classes import BusinessAttributeAssociationClass
from .....schema_classes import BusinessAttributeInfoClass
from .....schema_classes import BusinessAttributeKeyClass
from .....schema_classes import BusinessAttributesClass


BusinessAttributeAssociation = BusinessAttributeAssociationClass
BusinessAttributeInfo = BusinessAttributeInfoClass
BusinessAttributeKey = BusinessAttributeKeyClass
BusinessAttributes = BusinessAttributesClass

# fmt: on
